version: '3.8'
services:
  es01:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.0'
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - 'data01:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
    networks:
      - elastic
  kib01:
    image: 'docker.elastic.co/kibana/kibana:8.9.0'
    container_name: kib01
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: 'http://es01:9200'
      ELASTICSEARCH_HOSTS: 'http://es01:9200'
    depends_on:
      - es01
    networks:
      - elastic
  database:
    image: postgres:14-alpine
    container_name: got-db
    environment:
      - POSTGRES_DB=ASongOfIceAndFire
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=ASongOfIceAndFire
      - POSTGRES_URL="postgres://postgres:postgres@postgres:5432/ASongOfIceAndFire?sslmode=disable"
    ports:
      - '5434:5432'
    volumes:
      - ./.db/data:/var/lib/postgresql/data:delegated
      - ./.db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elastic
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  api:
    build:
      context: .
      dockerfile: GameOfThrones.API/Dockerfile
    ports:
      - '5100:5100'
    depends_on:
      - database
    container_name: game-of-thrones-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Elasticsearch__Uri=http://es01:9200
      - ConnectionStrings__DefaultConnection=Host=database;Database=ASongOfIceAndFire;Username=postgres;Password=postgres;PORT=5432
    networks:
      - elastic
    command: ["sh", "-c", "dotnet ef database update && dotnet GameOfThrones.API.dll"]

volumes:
  data01:
    driver: local
  postgres_data:
    driver: local
    
networks:
  elastic:
    driver: bridge
